### ISSUE TITLE
How to serialize and deserialize TimeSpan and DateTimeOffset

### ISSUE THREAD

**Issue by valentin-miroshnichenko** [QuickenLoans/XSerializer#41]
Hello, I would like to know how I can serialize and deserialize TimeSpan and DateTimeOffset. When I trying deserialize TimeSpan and DateTimeOffset I get an exception
![2015-04-10_10-51-37](https://cloud.githubusercontent.com/assets/10279529/7083876/995ce30a-df6f-11e4-9a9f-422b6ec857da.png)

**Comment by keithelder** [comment]
Been answered many times on Github. Should be easy to see how to fix this.

**Comment by valentin-miroshnichenko** [comment]
You mean something like this http://kennethxu.blogspot.ru/2008/09/xmlserializer-doesn-serialize-timespan.html
I'm looking for a replacement to the built-in XML serializaer to avoid such dramatical changes in my class =)

**Comment by keithelder** [comment]
More like this: http://stackoverflow.com/questions/637933/net-how-to-serialize-a-timespan-to-xml

**Comment by valentin-miroshnichenko** [comment]
I understand this approach but I need pure class without modifications. For example

public abstract class Message
    {
        public Guid SessionID { get; set; }

        public TimeSpan Interval { get; set; }

        public DateTimeOffset LocalTime { get; set; }
    }

**Comment by keithelder** [comment]
We'll have to think about and let you know if we find a way to do that.

**Comment by bfriesen** [comment]
I'll have an updated package available in an hour or too. Will support TimeSpan and DateTimeOffset.
