### ISSUE TITLE
XmlElement Attribute ignored on Interface

### ISSUE THREAD

**Issue by ori-emrlive** [QuickenLoans/XSerializer#71]
Consider this block:
```
public interface ILabel
 {
  [XmlElement(ElementName = "ITEM_ID", Order = 1)]
  string ItemId { get; set; }
  }

public class Label : ILabel
 {
  public string ItemId { get; set; }
  }
```
Wouldn't it make sense to serialize using the Interface Property Attribute(s), rather than the Class Property Attribute(s)?
Also, is there a way to make the root name Label when serializing ILabel?

TIA!

**Comment by bfriesen** [comment]
> Wouldn't it make sense to serialize using the Interface Property Attribute(s), rather than the Class Property Attribute(s)?

Yes it would. I'm currently working on a fix for this.

> Also, is there a way to make the root name Label when serializing ILabel?

You'll need to tell the serializer what the root element name should be. Like this:

```c#
var serializer = new XmlSerializer<ILabel>(x => x.SetRootElementName("Label"));
```

or this:

```c#
var serializer = new XmlSerializer<ILabel>(new XmlSerializationOptions(rootElementName:"Label"));
```

**Comment by bfriesen** [comment]
@ori-emrlive: This feature has been published. Release notes are here: [v0.3.7](/QuickenLoans/XSerializer/releases/tag/v0.3.7).
