### ISSUE TITLE
Escaped characters are not unescaped after deserialization

### ISSUE THREAD

**Issue by tbolyard** [QuickenLoans/XSerializer#77]
Deserializing a class property marked with the encrypt attribute containing characters that are escaped during serialization (e.g. &) results in the escaped character remaining.

I've submitted a pull request (#76) with a unit test.

**Comment by bfriesen** [comment]
I ran and debugged your unit test, and I see what you're talking about. However, if encrypting the value removes the escapable characters, and in your case it does, there the serialized value will not need to escape them. If you change your test around a little bit, you can see this:

```c#
[TestCase("Boots & cats & boots & cats")]
[TestCase("\"Double quotes\"")]
[TestCase("One < two")]
[TestCase("Two > one")]
[TestCase("What's up?")]
public void XmlSerializer_PropertyMarkedEncryptContainingEscapedCharsIsDeserialized_CharactersAreUnescaped(string expectedValue)
{
    var serializer = new XmlSerializer<Foo>(x => x
        .WithEncryptionMechanism(_base64EncryptionMechanism)
        .WithEncryptKey(typeof(Foo)));

    var xml = string.Format("<Foo><Bar>{0}</Bar></Foo>", _base64EncryptionMechanism.Encrypt(expectedValue));

    var actualValue = serializer.Deserialize(xml).Bar;

    Assert.AreEqual(expectedValue, actualValue);
}
```
